version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_fresh
    environment:
      POSTGRES_PASSWORD: postgres-db
      POSTGRES_DB: fruit
    ports:
      - 5555:5432
    networks:
      backend:
        aliases:
          - db
  api:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: fruits:dev
    container_name: fruits-api
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://db:5555/fruit
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  backend:
    name: network-backend
    driver: bridge
